### PR TITLE
fix: Upgrade go.mod package versions

### PR DESCRIPTION
**Pull request by VaniHaripriya**
Fixes #[RHOAIENG-13747](https://issues.redhat.com/browse/RHOAIENG-13747)

Implemented fixes on my fork and imported in my personal snyk account and made sure CVEs are eliminated. Attaching the screenshot for the same.

### CODE REVIEW

**Comment by VaniHaripriya** [comment]
Screenshot from 2024-10-11 17-17-36

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Review by gmfrasca — COMMENTED** [review]
if we're not promoting this to upstream, we should add the carry-commit prefix in the commit message

**Comment by gmfrasca** [comment]
also, should this not go to opendatahub-io/argo-workflows first?

**Comment by VaniHaripriya** [comment]
Closing this PR as the fixed versions of the packages responsible for the CVE are already present in the ODH main branch. These fixes will be incorporated into RHDS through the promotion process.

**Pull request closed without merging**
